name: KtLint workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
     # Runs KtLint on Rep.
    - name: Kotlin Linter
      uses: vroy/gha-kotlin-linter@v2


